### ISSUE TITLE
Default File Provisioning for Repo Request

### ISSUE THREAD

**Issue by m4s-b3n** [xpirit-training/demo-features-issueops#19]
how do we achieve specific files (e.g. CODE_OF_CONDUCT.md, CONTRIBUTING.md, CODEOWNERS, SUPPORT.MD) will be in the new repo?

there are 2 options:

1. store the files in this repo and make it selectable in the repo request issue form
2. have one (ore more) template repos to be selectable in the issue form

are there more options? 
which one should we choose?

## TODOs

- [ ] Add topics upon repository creation from issue form data
- [ ] Add default workflows to created repository
- [ ] Add Legitify as default workflow (@aatmmr)

**Comment by spindev** [comment]
@m4s-b3n I'm a fan of template repositories. Would start with a generic template with all the files and later create templates for specific use cases or specific applications / programming languages.

**Comment by m4s-b3n** [comment]
@spindev mee too, but this might result in a lot of duplication of files and increased update effort whenever one of these files changes.

**Comment by spindev** [comment]
@m4s-b3n That's true but a general problem for enterprise environments. Better would be linking to a central governance repository with all the common stuff. 

Adding a template repo as a starting point for requesting new repos is good addition for the demo part here. So feel free to add it :)

**Comment by m4s-b3n** [comment]
ok so here some details to make a decision...feel free to give feedback and add some pros/cons :)

## Option 1: template repos

### How To?

Multiple template repos containing all the files required for each repo. The issue form makes the templates selectable. Template will be utilized using `gh repo create --template <repository>`.

#### Pro

➕ keeps the management repo small & clean (specific files outside)
➕ less options within the issue form
➕ simply realizable

#### Con

➖ file duplication & maintenance for duplicated files (maybe with other issue templates and workflows? that may highly increase dependencies and complexity)
➖ automation for collecting the templates available in the issue form 

## Option 2: files within the repo

### How To?

All necessary files reside in the issue repo and can be selected (if there are multiple options/versions) within the issue form. Before creating the new repo the files will be added to toplevel and locally commited (no push). The new repo will be created using `gh repo create --push` transferring all local commits to the new repo.

#### Pro

➕ fully self contained solution
➕ automation easy as all of the files are within the repo (think of triggering workflows, handling files, permissions, tokens, ...)

#### Con

➖ scaling of the management repo
➖ more options within the issue form
➖  more complex to realize

**Comment by aatmmr** [comment]
The advantage I see in option 1 is that the template repos could be used manually as well and that the workflow/complexity is simpler. I, however, tend to option 2 to have a single source of truth.

I suggest: Let's keep both options in mind but build option 1 first 🚀
